#3 - create user api
tinhlesc/php_rest_api pull request #5
Opened 2022-03-04 03:36 UTC by tinhlesc

2022-03-04 13:24 UTC, tinhlesc commented on Controller/Api/UserController.php
> +        if (strlen($password) < 8) {
@tanthanhpham you should combine all condition into one if. It will similar your other cases.
```php
if (A || B || C) return false;
```

2022-03-05 02:39 UTC, tinhlesc commented on Controller/Api/UserController.php
> -        if (strlen($password) < 8 || strlen($password) > 20 || !$existNumber || !$existLetter || !$existCAPS) {
@tanthanhpham should read here: https://stackoverflow.com/questions/8141125/regex-for-password-php
<img width="748" alt="Screen Shot 2022-03-05 at 09 39 00" src="https://user-images.githubusercontent.com/26733563/156864685-ed64e110-09e9-4a36-a0c0-46ef3bebaca0.png">

2022-03-05 04:09 UTC, vtmkhue requested changes

2022-03-05 04:09 UTC, vtmkhue commented on Model/Database.php
> +    public function find($query = "", $params = [])
I think this function is just like select() function, you can re-use function select()

2022-03-16 06:58 UTC, merged