#4 - Delete user API
tinhlesc/php_rest_api pull request #6
Opened 2022-03-04 12:02 UTC by vtmkhue

- My feature: RESTful API - Delete user

2022-03-04 13:21 UTC, tinhlesc requested changes

2022-03-04 13:21 UTC, tinhlesc commented on Controller/Api/UserController.php
> +            } else if (count($arrQueryStringParams) > 0) {
@vtmkhue I don't think we need to delete with condition. We only need to id param.
In case, if id is exist, we will delete this user and that's enough.

2022-03-04 17:24 UTC, vtmkhue commented on Controller/Api/UserController.php
> +            } else if (count($arrQueryStringParams) > 0) {
I fixed this code, please check it again, thank you.

2022-03-05 02:10 UTC, tinhlesc requested changes

2022-03-05 02:10 UTC, tinhlesc commented on .gitignore
> +composer.json
@vtmkhue we need to keep composer.json and composer.lock in repo and push it to github.

2022-03-05 02:15 UTC, tinhlesc requested changes

2022-03-05 02:15 UTC, tinhlesc commented on Model/Database.php
> +                return "0 record deleded, your required not found.";
@vtmkhue should be return true/false, not string.

2022-03-05 03:53 UTC, tanthanhpham requested changes

2022-03-05 03:53 UTC, tanthanhpham commented on Controller/Api/UserController.php
> +            }
@vtmkhue I think you should notify the end user when the id is wrong

2022-03-05 03:53 UTC, tanthanhpham commented on Model/Database.php
> +        return $$isInserted;
@vtmkhue Please check line 59 again.
I think 
```php
$isInserted
```

2022-03-05 04:19 UTC, tinhthanhvo requested changes

2022-03-05 04:19 UTC, tinhthanhvo commented on Model/UserModel.php
> +        if (empty($username) && $username != "0") {
@vtmkhue I think 'username' field can't only contain string's 0. So, the condition may not be appropriate. You can fix with the condition for empty field.

2022-03-05 07:28 UTC, vtmkhue commented on .gitignore
> +composer.json
I'm so sorry that I don't know that, I pushed it this time, thank you.

2022-03-05 07:31 UTC, vtmkhue commented on Model/Database.php
> +                return "0 record deleded, your required not found.";
I fixed it, thank you.

2022-03-05 07:33 UTC, vtmkhue commented on Model/Database.php
> +                        $stmt->bind_param($k, $v[0], $v[1], $v[2], $v[3], $v[4]);
Ya, I used function executeStatement() instead, this function executeStatementWithMultiParam() I use for insert and update feature, thanks for remind me.

2022-03-05 07:36 UTC, vtmkhue commented on Model/UserModel.php
> +        foreach ($parram as $k => $v) {
I fixed it, sorry for the abbreviation.

2022-03-05 07:40 UTC, vtmkhue commented on Controller/Api/UserController.php
> +            }
I fixed it, thank you.

2022-03-05 07:41 UTC, vtmkhue commented on Model/Database.php
> +        return $$isInserted;
OMG, this is my bad, thank you a lot.

2022-03-05 07:45 UTC, vtmkhue commented on Model/UserModel.php
> +        if (empty($username) && $username != "0") {
Because I didn't check the minimum length for 'username' field, so end-user can input any value they want, include '0'. Thank you for remind me.

2022-03-16 02:53 UTC, merged